GLC:Lmb0z2Pmz7PIYrox5pLRZWTF8BldWQN+4kt7fEM/85wtkw==
GLC:gu2VorTtKxWE/pgXXZwDn/DxhRu7fMGuUzMu52e8FJVz8ky5c3s+V/nCu+EPUBw=
GLC:OFWnXvG4pvdnRryI9GNC5PSWat06aJoteaaDcfS7J4Qr9IGosQ==
GLC:247aT/T0dzlqnzHv14STRGNQyj9YDWcgKVMqM5H9E/jPPXyRZgdNfC6icuP6TB4=
GLC:agMDcXlZNrKxP0nTCAlUb3+x6N72z/AlfECaIFb28/cxu3KGW9liavQ=
GLC:5gEJefJHrLCMT4igO/n6gxGFNqHkMQ5VGol6Yd0z9Fpw5XL2+JV9ufKoX6HLI+yv7djWicPvNT3E
GLC:eNc1HM2iPwIoUrycE5cGr8dPkO6n8Qee+lSPsqWhWhJytyyUie4T89Eia7kT6LaHtg==
GLC:JL/R9bxINood6f7MXKG89PKPeTFhdiyGONBgWMHjl/wnCFmlvGtcDPGiJsW2Iwxn2VuiHDxlE/3VmA5AtuUQuhA=
GLC:bIqglYWnWmw96EYcaLPO5P+CDRJnCLfg2sunm60owzVNiCKeR1VGqldM4lXG3kZpUpgT
GLC:DmyN6lDkrfD5I7uSQYaupmTP7PkQjlaY/oku6r8THZA3d+EowwHuWpOSV/5eFvnkNnFpYLAAlkibpGJoYtEw1qEjlvDDX0LQJELK
GLC:PHhjssZbthU4hqeuBEKBs7mgP/8RvV4tln9DVihC+ydh6KtCNQ==
GLC:RfkUrvo8n8oFK5ouhTO8bW0+7qUFOp+fhqnEQYu5hUVicmDQren/5uV+/Ctl/k7IEg==
GLC:z1MIfeC7eS2ApcPjjWqF581G6opwa+jde7iQ0cyNwLq954SEDwvJzzEgM9sPQiWG0g==
GLC:TiakDmMYwVfSsKua3WL8tUXqSfb7EYxHfCosM0Rbp5oENpsza5GAZ2HcufIRE8KT4UcUSZ1dbQs=
GLC:PtWN4OAooSWK/BWJ9SBacR16/T6cQEGm/rw22Uyorp20n5FU2R1YzVkNdEIm1nWlyjOv
GLC:az9EePZ5C/soDrJU3pkJaQbL7orMmuxGFTw5EUS1Vjvd4PUGG1er9L1rji2eWHt92dNJv02X2ub0Tys=
GLC:km1/FasQSTFPQ056Rylz+ETYXxeeCkcW+0BFEtZIbiOA0RfVFGe8fofMAyhPqrAW2YIdO+oJT28bAg8X5+3fbsXaow==
GLC:DyITUU3bZG168awuyyOAalzAs/7EAwlWez0lx3bo1bq8ZQT1WkmH82q0AS+9lMFhksAEcWjBCdvVb8RkNy51V2zjLu7IVw==
GLC:BoZAvp3XtFDDkG+rYuVlHwsUKCD1yEGUOkQPy49tVXUzJieBWw==
GLC:O1V1YMNjOmqdJfOsmy9QwFnvKuK3op3FjrUox3+/0195pUMpDTOcyJilkwdBOgM9PkeeSRmNi+sn26M=
GLC:rWRo3ZM49Z3LMLTy8VeGBBfnmlnD5Ed6o31gHpdNZg+tus8a7qFrNF+0PLd+UKcwPMO+
GLC:Pkbs4gsElwAkU+jUaiY7kpHXZPSI1eqNbcL4oCeaov5CXfpw4XEorxndTluKInJ70z95hF93Ejul43CFrsHdqcI+FrKqB4O2XuczcWTrQ/3RzfhR
GLC:NrDIglNO/W11hRjhnHR4Omc7jRJtw/DBH65dCQ3BnJ3SwsdTN93+7Vlg+gqKT+brw7lGdMqZPD4nF7M=
GLC:ooCssa5RQwEVibRoHyOWhLuhK/+7k3mAA+QS/ajbIG5zysKH3dSLHawx0sfTavX6nQW2VEKGl/qMYO2xpbaw+sMBKPHh
GLC:HARjzY9it+GWcy/LM1Hn8h4fgNWZCGYRGxwUWQe9MgGMYlXutn4y5Ywn/9s5rJ1CN+R2QGtLMHTHkiImz00P
GLC:s/z9sx16+w8Xx9ZlsWuBHCr9FXVghaAz1liz7IBDCqz7EmTV2TjISoEszO/goOFE2A24Y2KgIuae+DyOlcF7Y0ZK7D4IYomjBe6CHui3BEFxxDDBlhfsxG4BNLA=
GLC:9+qt9n9UY+GiRhkdhMcvm8pgX47RNeAy9deyEsBUwrI5gzHIDw==
GLC:XkORGA8UHfkRxTZeF5L+8/I0f+Hl6B+GY/lfKJMcydplGQoo8AKZxhHWtWIC4KyOyg==
GLC:w9JPq4m0HUZB7PTp80L3g1ONDPmqguhHtDNBjp+f4hkKO+b6LjFfYAudk+o=
GLC:hpDmQ8x1DFXYQCEjENujrClOoodx5kzI/Aq2FobRMS+hEdZFcJfWxK94qBTkIKKPy5WkolVuo3MwVCIi/l1RAy8BfVo=
GLC:qAsmYt+59MJvSuV8VDYosJwKxHvZF8ZdNbu+IDrk9kDStdsjMNQOTLpOC3Mgr59Ohg==
GLC:oeqPloOQJ9ibA8XXDbCqYsmn5GCbyDcpp/5xwER0fXisPZhH1lt88szktLVe+eQXI5zGsmKYRQpU5PQ=
GLC:nckUxA1cVxZgUN241Cq/pR4rDyBejsO0YE6qOC36n/9wUhZIobZJ1ZISfHdA6sKngyWgOlvQiJc=
GLC:VR2cDJF/jWxhoL6XQDMAVk/ikJJTibyrzCbAFfP1fDA/DjH08Vnot+BisZCMePD9QSuvora9KNoPFSqJ1dGA9uLc637LSiIpAKrwwLxiyUxA7w==
GLC:/c6jEcRee3awSmlw1aBa3Meg//MAsElAIrXnIQtwTVLuAQh3vg==
GLC:I++PkwE/tbpb/IKObDSKTRrx8BpHrLsixs6fObovj/ew7EHhXcVWOqFfidDRmMr+7B4=
GLC:AhEXDB3WGu/XEv7obZIM4MZqzFZ3kg8YwGNwuinLmKTe3Klrbp2zY+qAOYkV
GLC:d363AmuZo9h+2iqsTgAiYvzYOB/5a+VwCHRFo6LgWvMNE3VDkfU8ribV9TSmDecXnDZs7dxN0yzTVlE7U0rpwndGHw==
GLC:S2hNSsjaf+0grQ4/io1v7RwdbCCjFtJ9oZEq26SLGQUfF51NdUshvpC+ajRNK4ym
GLC:z3wdxMgsTqoKErE7YOzCkTgz4l+pGDVeSRW2D8hCdXgYzMckWRH74k9M9id/VESJ1T60c9ZpFsbgJoBp
GLC:cgVB1Gic+Ono3UXuj1v6ICoaoXQ4l7kGvkuAzuXFWbQPh1dEEbqfHdvxevzST5shbXs+AmLa
GLC:UGiQLxVA2ymhI3lANv8nGdvIV7xug02hBCGnWtkVwCPA8OuXwNL4Dlb5gA9/jM5jdRMczm1zJu8rH5LzqPinCsWLC4ayvf4xeXaNWLQ5pG4=
GLC:yAI+PoOG+58yxHCQa7jN74kBjGyz7XNXLW4J63pSI3Mksgy/hw==
GLC:dtE1wfjNyQbBkW7W+BaAg80WHS8XucUOEvhvcuGO4nm8jpYTfp+Y2vv5vWb29sC1vrP8SPjQuA==
GLC:RW642icVpFBakg5XpEUigXPUBLc0s2Tq62rEZaj+Qu0mV7A2IRr1TUnYap1GJ1fQ
GLC:Ds7dhGJRN6XEU5g8d4jos+welRmUSd2ynA91g8H7ZFE9dta+R7kW8LvTzyNCW+CKNx2UP8ssPoVQcg0QecH30ds=
GLC:DQ/A5SK2jQhZUAnhzR94IrNbToa7M5b6acBUorCIs9PULty3EDXccI90vJ/7/c526A==
GLC:JL/R9bxINood6f7MXKG89PKPeTFhdiyGONBgWMHjl/wnCFmlvGtcDPGiJsW2Iwxn2VuiHDxlE/3VmA5AtuUQuhA=
GLC:8CGBgaxsUIUG97ZVUM4XlDoJsq/KD5J17HBcZzr0Iay3hsGCmfgjJeLkp9/O+0APlw7fYQ+U
GLC:ao91newyvj5QKvjr+5t56BlEcHWdEwBIlZh2OVIMRiFuI6i1Hd9cMjIbyz4i3GeUJeO1eRFWjnjausKfRkRlTAtkscj3fMx8yb6jfZA=
GLC:iTHq6I501kEXo1KkCPw8qf2H+ne8KfNQN5AbiDDR2SLzrzMT0w==
GLC:do86MYUPkzlwHRX82XiAUY4L3gQ0SOjQNxxbC2I9taGbL3RaOStb78K0aArk1kNyOsit
GLC:SlS9rVIffMuhLNDm5lXlCYMx7BT9fUogbKFMDTE9W5vp7IUgeWtTj/uVfaYSdHpIYubhdh2tnw==
GLC:dCCNRscr1pUYCSCBMniVSvoYUdl2tKoq64y/cgCGSzmtzg7UlSTitnIB3JaGTTyEzERnIYCMtRQbbkncGF2VChSfuz+hkzGH2l5Q5o+s7H/k5WcjVCjw7lOU
GLC:2HhEPxjFSC/BZT1ScDpbN3LXkja/s8LIaoEsr5C7EE74uCswVPPF+Px8KicGoq2QmLGacGmJYbOB5eNRkKh4
GLC:Kgfr4PoEA8Rh17lMzJK52U7s6YM3OmLwHM/8jvkNxdW0ov2sXEOjcXYUKxjCHnBgOd5TBvXgbi0YxipjAtd9rrlfC2fGGSOlgP0RA3+11AoivtzCvDczXbFkIHU=
GLC:7PbmxEvxI9Xfx8ml8FIbtGc2/WrueTS5poN0s4xeuZj2HL5y7YjY+WApy8dFEOQDHhoHo5y5jJCQAQ==
GLC:/UNytjbZVTZqLQasKJoet2NHAOhYHyrQNPAF2Pcf2jNdT/ntzrTMlGTRdf0wpwqxJPwk8GHq7TTeGuC+YyhsYBAkz5FwsvOi/XCzpc7ZtHkAALsDgLAkC19PUz33VUSLA2v+gvkuuLz8IbO8
GLC:L2ILlsjC7XR+WVMJFDElXWIse3Umtim0L4BUUVUvYAASN/X9Wg==
GLC:oCpEf4RPZE1xVnaz24B16248pjwdN+2Hw/zYB2pWMkKe3CaQW23Ja1IF059S
GLC:8FrF7vdfg87fitEEYdjYRregb12YSpK1ugwE80tpprGA9y4l53nxLN7AShjBOw==
GLC:OkwW8GHXxC/W4vqazdOtjdN96zHcvI9qtKMpRLe5YjR28USQ9P85/1fSOmmLK8f/Ze7e6OMb
GLC:PD/PW5aDn9GoxPCzmLV+/WHclE5vIzg/vqdViFaNAQKjBcQsEucyiRqPn+imnnY=
GLC:0ZJr7zNEWVgold3xjN40WkCBpakpgGG8w6Osy4xn7dD7fLTcW9NSz7WFP9a4Ig7E6E+FQ16dwA==
GLC:ugd/UIn9XiFa/f62d3rmW7CYDWkBaWHLBHIAJYfrB3h7IR7yDS4fgSBoD9O7Tpf7xFd6
GLC:CApu5MSewnAJkIb8aCVRBPimJrDtL9uPOP+DnWdxlOz/IISM1cbhW5HVbBS5+ubQt6BnMABWCcbMAkM1rLu3fuTSTXM=
GLC:Vqg2zXjr9cDBRIx6ULYR0lFzz/NLWfD8Tu8UkZrGN83ELI47/w==
GLC:qXK52rvv9dcAr7SIQg/CI9qK91N2w/60Hy6sug5e1FX4aZTRPLCOq5PSnlBUqUNr1w==
GLC:3zUL43YSCK24HDy/trmPhHS1aLQzzP52DIldBUiO2Sq5hMmwnbsIqvof+Kg=
GLC:dbKM3HF/Rchjv1Dk62UZ7QNeGXWREKTqxFpVIVYRLeZRB6+OUGkQkoWa9V9NsfZU4dB5FCricCQ9xQOckNJr4wlZEMTw
GLC:Gu8c0EPF456CXO15Jq0PlQjzyCs4Rz1B3E91ULYzMdflWjsIROe63jRnW4wV1lGbWw==
GLC:JL/R9bxINood6f7MXKG89PKPeTFhdiyGONBgWMHjl/wnCFmlvGtcDPGiJsW2Iwxn2VuiHDxlE/3VmA5AtuUQuhA=
GLC:5ZwSfC32tsLfbOTyk9r2UCegDKEKh3FuLjLnIeRWkiOMMvFnv+Vk+ccBkZE7KBXfxds0pe4iNbax
GLC:pT5lKAh7YdFQOtOLFAvAHgUTGWPL/SnbdZv8lrhv49QlelBojjU6vlkf8oYW+HdIR8AxwvTVk6+nNmvUYzGNnio5BOj9/7YYF/egKn0=
